### ISSUE TITLE
[META] Переработка структуры содержимого

### ISSUE THREAD

**Issue by Niklan** [Druki-ru/website#46]
У [MDN](https://github.com/mdn/content) достаточно интересное решение по организации репозитория с контентом.

В их случае контент = папка в которой есть index.md.

- В папках не будет смешанных материалов
- Рядом с файлом можно даже хранить какие-то драфты \ ридми \ файлы.
- Не нужно придумывать ID материала, можно юзать путь за ID: /drupal/hooks/create = drupal-hooks-create.

Что нужно сделать:

- [x] #49 - Добавить поддержку редиректов.
- [x] #50 Переписать поиск файлов на данную структуру.
- [x] #52 Добавить новый обязательный параметр Front Matter в документ - `slug`. Он заменит текущий `path` (удалить). Например, `slug: drupal/9/hooks` будет использоваться сайтом для генерации пути, где `/wiki` добавляется на уровне сайта - `slug` путь документа = `/wiki/drupal/9/hooks`.
- [x] #51 Переписать логику для External ID, убрать поддержку `id` параметра в Front Matter.
- [x] Переработать репозиторий с контентом под эту структуру. Делать будется в процессе введения конкретных изменений. Внедрятся будут не скопом, а в указанном порядке.
